version: '3.8'
services:
  mongodb:
    image: mongo
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}

  backend:
    depends_on:
      - mongodb
    build: ./backend
    ports:
      - 80:80
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}

  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true

volumes:
  data:
  logs:
